services:
  influx_local:
    image: influxdb:2
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: energy
      DOCKER_INFLUXDB_INIT_PASSWORD: energypass123
      DOCKER_INFLUXDB_INIT_ORG: energy-org
      DOCKER_INFLUXDB_INIT_BUCKET: energy
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: energy-token-123
    volumes:
      - influxdata:/var/lib/influxdb2
    networks: [energy_net]

  generator:
    image: python:3.11-slim
    working_dir: /app
    volumes:
      - .:/app:ro
    env_file:
      - ../../.env
    command: ["bash","-lc","pip install --no-cache-dir influxdb-client paho-mqtt && python /app/generator.py"]
    environment:
      LOCAL_INFLUX_URL: http://influx_local:8086
      LOCAL_ORG: energy-org
      LOCAL_BUCKET: energy
      LOCAL_TOKEN: energy-token-123
      SITE_ID: site-a
      ENERGY_RATE: "0.25"
      MQTT_BROKER_HOST: mqtt.local
      MQTT_BROKER_PORT: "1883"
      CENTRAL_INFLUX_URL: http://influx.local:8086
      CENTRAL_INFLUX_ORG: ${INFLUX_ORG}
      CENTRAL_INFLUX_BUCKET: ${INFLUX_BUCKET}
      CENTRAL_INFLUX_TOKEN: ${INFLUX_TOKEN}
    depends_on: [influx_local]
    networks: [energy_net, main_net]

  ui:
    image: python:3.11-slim
    working_dir: /app
    volumes:
      - ./ui:/app
    env_file:
      - ../../.env
    command: ["bash","-lc","pip install --no-cache-dir cherrypy influxdb-client && python /app/app.py"]
    environment:
      ENERGY_INFLUX_URL: http://influx_local:8086
      ENERGY_INFLUX_ORG: energy-org
      ENERGY_INFLUX_BUCKET: energy
      ENERGY_INFLUX_TOKEN: energy-token-123
    ports:
      - "3002:8000"
    depends_on: [influx_local]
    networks: [energy_net]

networks:
  energy_net: {}
  main_net:
    external: true
    name: dt_polyglot_db_default

volumes:
  influxdata: {}
