apiVersion: v1
kind: Service
metadata:
  name: reactui
  namespace: dtp
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30083
    name: http
  selector:
    app: reactui

