apiVersion: 1
datasources:
  - name: LiftLocalInflux
    uid: lift_local
    type: influxdb
    access: proxy
    url: http://lift_influx:8086
    jsonData:
      version: Flux
      organization: lift-org
      defaultBucket: lift
    secureJsonData:
      token: admin-token
    isDefault: true
