apiVersion: v1
kind: Secret
metadata:
  name: influx-secret
  namespace: dtp
type: Opaque
stringData:
  DOCKER_INFLUXDB_INIT_MODE: setup
  DOCKER_INFLUXDB_INIT_USERNAME: dtpuser
  DOCKER_INFLUXDB_INIT_PASSWORD: dtpsecret1
  DOCKER_INFLUXDB_INIT_ORG: dtp-org
  DOCKER_INFLUXDB_INIT_BUCKET: signals
  DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: dtp-token-123456

