apiVersion: apps/v1
kind: Deployment
metadata:
  name: reactui
  namespace: dtp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reactui
  template:
    metadata:
      labels:
        app: reactui
    spec:
      containers:
      - name: reactui
        image: dtp-react:dev
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
          name: http

