apiVersion: v1
kind: ConfigMap
metadata:
  name: mqtt-config
  namespace: dtp
data:
  mosquitto.conf: |
    persistence true
    persistence_location /mosquitto/data/
    listener 1883 0.0.0.0
    allow_anonymous true

