apiVersion: v1
kind: Service
metadata:
  name: django
  namespace: dtp
spec:
  type: NodePort
  ports:
  - port: 8000
    targetPort: 8000
    nodePort: 30084
    name: http
  selector:
    app: django

